inicio

    texto nome
    texto genero

    escrever "Digite o seu nome: "
    ler nome
    
    escrever "Digite o seu gênero (Homem/Mulher): "
    ler genero
    
     escolhe genero
        caso "Homem":
            escrever "Olá Sr. ", nome
        caso "Mulher":
            escrever "Olá Sra. ", nome
        defeito:
            escrever "Gênero inválido. Por favor, digite 'Homem' ou 'Mulher'."
    fimEscolhe
    
fim


